.TH man 1 "25 June 2015" "0.1.1" "rtee man page"
.SH NAME
.PP
rtee \- read from standard input and write to standard output and
rotating files
.SH SYNOPSIS
.PP
rtee [OPTION]...
[FILE]...
.SH DESCRIPTION
.PP
\-a        Append to the given FILE.
.PP
\-b num    Maximum number of bytes per file (default 1M)
.PP
\-f num    Maximum number of previous files before rotating (default 4)
.PP
\-B num    buffer size of read/write operation (default 8192
.PP
\-h        Display help.
.PP
The FILE name is appended with the count starting at FILE.0.
When the maximum number of files is reached, the oldest one is deleted
and the file number continues to increment.
.SH EXAMPLES
.PP
To create 5 backup files with a size of 10 KB or less of
the listing of files found in your OS.
.PP
find / | rtee \-b 10000 \-f 5 listing.txt
.PP
This will output files named \f[I]listing.txt.N\f[] with 6 files, the
highest number being the latest.
.SH AUTHOR
.PP
Written by Jeff Parent.
.SH REPORTING BUGS
.PP
Report bugs to <bugs@commentedcode.org>
.SH COPYRIGHT
.PP
Copyright (c) 2015, Jeff Parent All rights reserved.
.PP
Copyright (c) 1988, 1993
The Regents of the University of California.  All rights reserved.
